### ISSUE TITLE
Project name too generic

### ISSUE THREAD

**Issue by cjus** [dynamsoft-dbr/webassembly#4]
Recommend changing the project repo name as it's too generic.
Perhaps `dbr-wasm` or `dbr-webassembly`

**Comment by yushulx** [comment]
Thanks for your suggestion. Please take a look at the URL https://github.com/dynamsoft-dbr/webassembly. If name **dbr-webassembly**, it will be `https://github.com/dynamsoft-dbr/dbr-webassembly`. **dbr/dbr** doesn't look good. This is why the repo was not named **dbr-webassembly**.
