### ISSUE TITLE
Issue decoding DataMatrix barcode

### ISSUE THREAD

**Issue by cjus** [dynamsoft-dbr/webassembly#5]
I changed this single line in the project to test another barcode and received the following error:

```javascript
var source = fs.readFileSync('datamatrix.png');
```

```shell
$ node index.js
failed to asynchronously prepare wasm: RuntimeError: float unrepresentable in integer range
RuntimeError: float unrepresentable in integer range
    at wasm-function[200]:21
    at wasm-function[7871]:2189
    at wasm-function[3325]:17
    at Object.c.dynCall_iiii (/webassembly/node_modules/dbrjs/dist/dbr.min.js:194:53)
    at invoke_iiii (/webassembly/node_modules/dbrjs/dist/dbr.min.js:119:224)
    at wasm-function[7174]:4159
    at wasm-function[3287]:19
    at Object.c.dynCall_viiii (/webassembly/node_modules/dbrjs/dist/dbr.min.js:203:55)
    at invoke_viiii (/webassembly/node_modules/dbrjs/dist/dbr.min.js:133:200)
    at wasm-function[7177]:577
RuntimeError: float unrepresentable in integer range
    at wasm-function[200]:21
    at wasm-function[7871]:2189
    at wasm-function[3325]:17
    at Object.c.dynCall_iiii (/webassembly/node_modules/dbrjs/dist/dbr.min.js:194:53)
    at invoke_iiii (/webassembly/node_modules/dbrjs/dist/dbr.min.js:119:224)
    at wasm-function[7174]:4159
    at wasm-function[3287]:19
    at Object.c.dynCall_viiii (/webassembly/node_modules/dbrjs/dist/dbr.min.js:203:55)
    at invoke_viiii (/webassembly/node_modules/dbrjs/dist/dbr.min.js:133:200)
    at wasm-function[7177]:577
```

This barcode decodes using the [i-nigma](https://play.google.com/store/apps/details?id=com.threegvision.products.inigma.Android&hl=en_US) android barcode scanner to `00000203.000001.02.02.01.01.0` 

![datamatrix](https://user-images.githubusercontent.com/387129/43642645-69bd1448-96f6-11e8-84ee-6ecc03b412d5.png)

**Comment by yushulx** [comment]
If you visit https://demo.dynamsoft.com/DBR/BarcodeReaderDemo.aspx, you can get the same result.
![datamatrix](https://user-images.githubusercontent.com/2202306/43643490-03830b52-975e-11e8-959e-2f5a66114d03.PNG)

The error means it failed to read the barcode. The WebAssembly edition, compiled by Emscripten, is not as good as [Node.js C++ addon](https://github.com/dynamsoft-dbr/linux-barcode-sdk-node-wrapper). It's an unavoidable issue caused by compilation (C++ to JavaScript), not algorithm itself.  Currently, you can use ```try...catch...``` to process this issue.

```javascript
try {
        let results = dbr.DecodeFileInMemory(typedArray, "");
        console.timeEnd('wasm');
        let json = JSON.parse(results);
        let barcodeResults = json['textResult'];
        let txts = [];
        for (let i = 0; i < barcodeResults.length; ++i) {
            txts.push(Buffer.from(barcodeResults[i].BarcodeText, 'base64').toString('ascii'));
        }
        console.log(txts.join(", "));
    } catch (error) {
        console.log(error);
    }
```

**Comment by cjus** [comment]
@yushulx thanks!  The sample code index.js should probably have the try/catch as well. I did run into an issue with the Node.js C++ addon but posted the issue [here](https://github.com/yushulx/nodejs-barcode-for-win-linux-mac/issues/1) I was unaware of the link you posted above. I see it's setup for the 6.2 sdk so I'll give that a try.  Thanks again!
